language: node_js
node_js:
  - 12

branches:
  only:
    - master
    - "/^v?[0-9\\.]+/"

deploy:
  provider: npm
  email: "noreply@yokotakenji.me"
  on:
    tags: true
  api_key:
    secure: "O+7V1ch1DccQEEo4Uuxc5QHPunXQ8bDrzt1H1Ayty38nhp1nQaf0TdnmtsIpixiUYpeo0GoQL/k62aB3o4VQj7yOTSm7NGtkMbynDDIOWF5alQcdWU0qOGhKOcS+MnbmDdg8CSQkZn+5GLGerCjK8ycsoFKiUdhQUy9Z9wLI2PW/kYj+A0xG4GCVFSfrVYJ1irZiGdtWZIrCTMTNDkEYmLP6/Jc0yAYN8nl/dz85t4xzv5+5v5xujQv0oAM9SH5AtNirtuCxmf6R5VtV4FZSv2qZ01l7BDerFd0fqKKiCsn3ZqTyhV7OyIldZNOMKKCiyNt2FwJOU44ny+g42X3Nm2gC0jAFr39sZjN0GdcXM0ZxWL9R758ph4mDNz/GOlMHFfdJQNIEsqJmExPNW8v1tDDAXa8HLKRsyUyQcCUnOSh1a0zJxp+nfYUQVG+Wb8foyVfrEMgKheL+ZaDwb6QtzA7LWX7v385d3Ruk4hMlEfj+29koIyQ9YBjGebZyLq+x0sn3j/WBJTdUx+x50y0kA/LBTvMvra9baiK+iiR6IKeqYZMi/oXfWD2fRvJFPOgIb2UmxujW+YV2Iy31KCR5ISOJA8bW+wolps9by2Pc5Rkfl4+sBXJ8X8azZrc5grNKtYMuv0pJR7jVczys2fUA8iwEW1O1iNxyg8fUPkFK6VE="
