language: node_js
node_js:
  - 8.9.3
sudo: false
cache:
  directories:
    - node_modules
after_success:
  - npm install -g codecov
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
